### ISSUE TITLE
fullwidth tilde / wave dash problem.

### ISSUE THREAD

**Issue by ataniazov** [SethClydesdale/typing-with-mishy#4]
The game in the texts like:
'みししっ、たのしんでいってね～！',
'きーあ、みっしぃにきっくをしたいかな～！',
'おにいちゃん～',
'きゃっ、みつかっちゃった～',
'みししっ、のろまなみっしぃおにいちゃんとはおおちがいだよ～',
expects  ～ (Unicode U+FF5E ～ FULLWIDTH TILDE).
It works on Japanese IME for Windows platform but it is not working on systems like Linux and Android.
Because Japanese IME like Mozc gives 〜 (Unicode U+301C 〜 WAVE DASH) by default.
Is it possible to make game accept both full-width tilde and wave dash?

Thanks for awesome japanese typing practice game.

**Comment by SethClydesdale** [comment]
Hello @ataniazov, thank you for reporting this bug! It should be possible to fix by replacing the 〜 in the input with ～ in `highlightText()` and `checkAnswer()`. I'll go ahead and do that right now 👍

**Comment by SethClydesdale** [comment]
It should be fixed now. If the issue is still persisting, let me know. Thanks again!

**Comment by ataniazov** [comment]
Yep, now it accepts both inputs.
ありがとうございます。
